name: gwas
channels:
  - anaconda
  - conda-forge
  - defaults
  - r
dependencies:
  - gxx_linux-64
  - jupyter
  - libopenblas
  - python=3.7
  - r-compositions
  - r-ggfortify
  - r-irkernel
  - r-bayesm
