---
title: "V gene usage PCA"
output:
  html_document:
    toc: true
    toc_depth: 2
    dev: 'svg'
---
```{r echo=TRUE, message=FALSE, warning=FALSE}

library("compositions")

knitr::opts_chunk$set(fig.width=16, fig.height=8)

data_sets =
    structure(
              c("data/emerson_vfam_in_frame_frequencies.tsv",
                "data/emerson_vfam_out_frame_frequencies.tsv",
                "data/emerson_vgene_in_frame_frequencies.tsv",
                "data/emerson_vgene_out_frame_frequencies.tsv"),
              names=c("family_in_frame",
                      "family_out_frame",
                      "gene_in_frame",
                      "gene_out_frame"))


pseudocount_is_the_min_element_divided_by_this = 10.
only_allow_genes_with_max_frequency_greater_than = 0.005
min_total_tcr_count = 1000

read_merged_by_name = function(data_set_name) {
    data = read.table(data_sets[data_set_name], header = TRUE)
    deletion_genotypes = read.table("data/TRB_deletion_genotypes.tsv", header = TRUE)
    merge(deletion_genotypes, data, by="hipid")
}

subsetted_freqs_from_data_with_pseudocount = function(freqs) {
    freqs = freqs[apply(freqs, 2, max) > only_allow_genes_with_max_frequency_greater_than]
    min_freq = min(freqs[freqs > 0])
    freqs = freqs + min_freq/pseudocount_is_the_min_element_divided_by_this
    freqs / rowSums(freqs)
}

cleaned_data_with_genotypes_by_name = function (data_set_name) {
    merged = read_merged_by_name(data_set_name)
    merged = merged[merged$total_tcrs >= min_total_tcr_count,]
    freqs = subsetted_freqs_from_data_with_pseudocount(merged[6:NCOL(merged)])
    cleaned = cbind(merged["genotype_str"], freqs)
    rownames(cleaned) = merged$hipid
    cleaned
}

plot_pca = function(data_set_name, compositional) {
    analysis_type = if(compositional) "compositional" else "naive"
    cleaned = cleaned_data_with_genotypes_by_name(data_set_name)
    for (genotype in unique(cleaned$genotype_str)) {
        freqs = cleaned[cleaned$genotype_str == genotype, 2:NCOL(cleaned)]
        full_data_set_name = paste(data_set_name, genotype, sep="-")
        pc = princomp(acomp(freqs))
        title = paste(analysis_type, full_data_set_name, sep="-")
        par(mfrow=c(1,2))
        biplot(pc, main=title, expand=0.8)
        plot(pc, main=title)
        write.csv(pc$scores[,1:10], file=paste0("_ignore/", title, ".csv"))
    }
}

plot_both_pcas = function(data_set_name) {
    plot_pca(data_set_name, FALSE)
    plot_pca(data_set_name, TRUE)
}

```


```{r warning=FALSE, results='hide'}

lapply(names(data_sets), plot_both_pcas)

```
