visualizations.html:visualizations.Rmd 
	R -e "rmarkdown::render('visualizations.Rmd')"

visualize_genome.html:visualize_genome.Rmd 
	R -e "rmarkdown::render('visualize_genome.Rmd')"

visualize_specific_file.html:visualize_specific_file.Rmd 
	R -e "rmarkdown::render('visualize_specific_file.Rmd')"
